# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GCSguiWUcide.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QLCDNumber,
    QLabel, QPushButton, QSizePolicy, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1091, 776)
        self.simEnable = QPushButton(Dialog)
        self.simEnable.setObjectName(u"simEnable")
        self.simEnable.setGeometry(QRect(780, 600, 111, 24))
        self.simActivate = QPushButton(Dialog)
        self.simActivate.setObjectName(u"simActivate")
        self.simActivate.setGeometry(QRect(780, 650, 111, 24))
        self.calAltitude = QPushButton(Dialog)
        self.calAltitude.setObjectName(u"calAltitude")
        self.calAltitude.setGeometry(QRect(780, 700, 111, 24))
        self.totMissionTime = QLCDNumber(Dialog)
        self.totMissionTime.setObjectName(u"totMissionTime")
        self.totMissionTime.setGeometry(QRect(170, 70, 64, 23))
        self.totMissionTimeLabel = QLabel(Dialog)
        self.totMissionTimeLabel.setObjectName(u"totMissionTimeLabel")
        self.totMissionTimeLabel.setGeometry(QRect(50, 70, 101, 16))
        self.packetCountLabel = QLabel(Dialog)
        self.packetCountLabel.setObjectName(u"packetCountLabel")
        self.packetCountLabel.setGeometry(QRect(50, 110, 71, 16))
        self.packetCount = QLCDNumber(Dialog)
        self.packetCount.setObjectName(u"packetCount")
        self.packetCount.setGeometry(QRect(170, 110, 64, 23))
        self.modeLabel = QLabel(Dialog)
        self.modeLabel.setObjectName(u"modeLabel")
        self.modeLabel.setGeometry(QRect(50, 150, 71, 16))
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(440, 20, 201, 16))
        self.mode = QLabel(Dialog)
        self.mode.setObjectName(u"mode")
        self.mode.setGeometry(QRect(170, 150, 21, 16))
        self.stateLabel = QLabel(Dialog)
        self.stateLabel.setObjectName(u"stateLabel")
        self.stateLabel.setGeometry(QRect(50, 180, 71, 16))
        self.state = QLabel(Dialog)
        self.state.setObjectName(u"state")
        self.state.setGeometry(QRect(170, 180, 71, 16))
        self.altitudeLabel = QLabel(Dialog)
        self.altitudeLabel.setObjectName(u"altitudeLabel")
        self.altitudeLabel.setGeometry(QRect(50, 210, 71, 16))
        self.altitude = QLCDNumber(Dialog)
        self.altitude.setObjectName(u"altitude")
        self.altitude.setGeometry(QRect(170, 210, 64, 23))
        self.temperatureLabel = QLabel(Dialog)
        self.temperatureLabel.setObjectName(u"temperatureLabel")
        self.temperatureLabel.setGeometry(QRect(50, 250, 71, 16))
        self.temperature = QLCDNumber(Dialog)
        self.temperature.setObjectName(u"temperature")
        self.temperature.setGeometry(QRect(170, 250, 64, 23))
        self.pressureLabel = QLabel(Dialog)
        self.pressureLabel.setObjectName(u"pressureLabel")
        self.pressureLabel.setGeometry(QRect(50, 290, 71, 16))
        self.pressure = QLCDNumber(Dialog)
        self.pressure.setObjectName(u"pressure")
        self.pressure.setGeometry(QRect(170, 290, 64, 23))
        self.voltageLabel = QLabel(Dialog)
        self.voltageLabel.setObjectName(u"voltageLabel")
        self.voltageLabel.setGeometry(QRect(50, 330, 71, 16))
        self.voltage = QLCDNumber(Dialog)
        self.voltage.setObjectName(u"voltage")
        self.voltage.setGeometry(QRect(170, 330, 64, 23))
        self.currentLabel = QLabel(Dialog)
        self.currentLabel.setObjectName(u"currentLabel")
        self.currentLabel.setGeometry(QRect(50, 370, 71, 16))
        self.current = QLCDNumber(Dialog)
        self.current.setObjectName(u"current")
        self.current.setGeometry(QRect(170, 370, 64, 23))
        self.gyroRLabel = QLabel(Dialog)
        self.gyroRLabel.setObjectName(u"gyroRLabel")
        self.gyroRLabel.setGeometry(QRect(220, 410, 91, 16))
        self.gyroR = QLCDNumber(Dialog)
        self.gyroR.setObjectName(u"gyroR")
        self.gyroR.setGeometry(QRect(140, 450, 64, 23))
        self.pitchAxisLabel = QLabel(Dialog)
        self.pitchAxisLabel.setObjectName(u"pitchAxisLabel")
        self.pitchAxisLabel.setGeometry(QRect(20, 500, 51, 16))
        self.AcceleromterR = QLCDNumber(Dialog)
        self.AcceleromterR.setObjectName(u"AcceleromterR")
        self.AcceleromterR.setGeometry(QRect(300, 450, 64, 23))
        self.yawAxisLabel = QLabel(Dialog)
        self.yawAxisLabel.setObjectName(u"yawAxisLabel")
        self.yawAxisLabel.setGeometry(QRect(20, 550, 51, 16))
        self.gyroY = QLCDNumber(Dialog)
        self.gyroY.setObjectName(u"gyroY")
        self.gyroY.setGeometry(QRect(300, 550, 64, 23))
        self.gyroYLabel_2 = QLabel(Dialog)
        self.gyroYLabel_2.setObjectName(u"gyroYLabel_2")
        self.gyroYLabel_2.setGeometry(QRect(220, 550, 81, 16))
        self.rollAxisLabel = QLabel(Dialog)
        self.rollAxisLabel.setObjectName(u"rollAxisLabel")
        self.rollAxisLabel.setGeometry(QRect(20, 450, 51, 16))
        self.gyroRLabel_2 = QLabel(Dialog)
        self.gyroRLabel_2.setObjectName(u"gyroRLabel_2")
        self.gyroRLabel_2.setGeometry(QRect(100, 450, 31, 16))
        self.accelerometerRLabel = QLabel(Dialog)
        self.accelerometerRLabel.setObjectName(u"accelerometerRLabel")
        self.accelerometerRLabel.setGeometry(QRect(220, 450, 81, 16))
        self.gyroPLabel_5 = QLabel(Dialog)
        self.gyroPLabel_5.setObjectName(u"gyroPLabel_5")
        self.gyroPLabel_5.setGeometry(QRect(100, 500, 31, 16))
        self.gyroR_2 = QLCDNumber(Dialog)
        self.gyroR_2.setObjectName(u"gyroR_2")
        self.gyroR_2.setGeometry(QRect(140, 500, 64, 23))
        self.gyroPLabel_6 = QLabel(Dialog)
        self.gyroPLabel_6.setObjectName(u"gyroPLabel_6")
        self.gyroPLabel_6.setGeometry(QRect(220, 500, 81, 16))
        self.AcceleromterR_2 = QLCDNumber(Dialog)
        self.AcceleromterR_2.setObjectName(u"AcceleromterR_2")
        self.AcceleromterR_2.setGeometry(QRect(300, 500, 64, 23))
        self.gyroYLabel_3 = QLabel(Dialog)
        self.gyroYLabel_3.setObjectName(u"gyroYLabel_3")
        self.gyroYLabel_3.setGeometry(QRect(100, 550, 31, 16))
        self.gyroY_2 = QLCDNumber(Dialog)
        self.gyroY_2.setObjectName(u"gyroY_2")
        self.gyroY_2.setGeometry(QRect(140, 550, 64, 23))
        self.magRoll = QLCDNumber(Dialog)
        self.magRoll.setObjectName(u"magRoll")
        self.magRoll.setGeometry(QRect(480, 450, 64, 23))
        self.magRollLabel = QLabel(Dialog)
        self.magRollLabel.setObjectName(u"magRollLabel")
        self.magRollLabel.setGeometry(QRect(390, 450, 91, 16))
        self.magYaw = QLCDNumber(Dialog)
        self.magYaw.setObjectName(u"magYaw")
        self.magYaw.setGeometry(QRect(480, 550, 64, 23))
        self.magPitch = QLCDNumber(Dialog)
        self.magPitch.setObjectName(u"magPitch")
        self.magPitch.setGeometry(QRect(480, 500, 64, 23))
        self.magYawLabel = QLabel(Dialog)
        self.magYawLabel.setObjectName(u"magYawLabel")
        self.magYawLabel.setGeometry(QRect(390, 550, 81, 16))
        self.magPitchLabel = QLabel(Dialog)
        self.magPitchLabel.setObjectName(u"magPitchLabel")
        self.magPitchLabel.setGeometry(QRect(390, 500, 81, 16))
        self.autoGyroLabel = QLabel(Dialog)
        self.autoGyroLabel.setObjectName(u"autoGyroLabel")
        self.autoGyroLabel.setGeometry(QRect(190, 600, 111, 16))
        self.autoGyroRate = QLCDNumber(Dialog)
        self.autoGyroRate.setObjectName(u"autoGyroRate")
        self.autoGyroRate.setGeometry(QRect(310, 600, 64, 23))
        self.GPSInfoLabel = QLabel(Dialog)
        self.GPSInfoLabel.setObjectName(u"GPSInfoLabel")
        self.GPSInfoLabel.setGeometry(QRect(240, 640, 91, 16))
        self.GPSTime = QLCDNumber(Dialog)
        self.GPSTime.setObjectName(u"GPSTime")
        self.GPSTime.setGeometry(QRect(70, 680, 64, 23))
        self.GPSTimeLabel = QLabel(Dialog)
        self.GPSTimeLabel.setObjectName(u"GPSTimeLabel")
        self.GPSTimeLabel.setGeometry(QRect(30, 680, 31, 16))
        self.GPSAltitudeLabel = QLabel(Dialog)
        self.GPSAltitudeLabel.setObjectName(u"GPSAltitudeLabel")
        self.GPSAltitudeLabel.setGeometry(QRect(150, 680, 41, 16))
        self.GPSAltitude_2 = QLCDNumber(Dialog)
        self.GPSAltitude_2.setObjectName(u"GPSAltitude_2")
        self.GPSAltitude_2.setGeometry(QRect(200, 680, 64, 23))
        self.GPSLatitudeLabel = QLabel(Dialog)
        self.GPSLatitudeLabel.setObjectName(u"GPSLatitudeLabel")
        self.GPSLatitudeLabel.setGeometry(QRect(280, 680, 51, 16))
        self.GPSLatitude = QLCDNumber(Dialog)
        self.GPSLatitude.setObjectName(u"GPSLatitude")
        self.GPSLatitude.setGeometry(QRect(330, 680, 64, 23))
        self.GPSLongitudeLabel = QLabel(Dialog)
        self.GPSLongitudeLabel.setObjectName(u"GPSLongitudeLabel")
        self.GPSLongitudeLabel.setGeometry(QRect(410, 680, 61, 16))
        self.GPSLongitude = QLCDNumber(Dialog)
        self.GPSLongitude.setObjectName(u"GPSLongitude")
        self.GPSLongitude.setGeometry(QRect(470, 680, 64, 23))
        self.GPSsatsLabel = QLabel(Dialog)
        self.GPSsatsLabel.setObjectName(u"GPSsatsLabel")
        self.GPSsatsLabel.setGeometry(QRect(220, 730, 31, 16))
        self.GPSsats = QLCDNumber(Dialog)
        self.GPSsats.setObjectName(u"GPSsats")
        self.GPSsats.setGeometry(QRect(250, 730, 64, 23))
        self.CMDEchoLabel = QLabel(Dialog)
        self.CMDEchoLabel.setObjectName(u"CMDEchoLabel")
        self.CMDEchoLabel.setGeometry(QRect(260, 230, 61, 16))
        self.CMDEcho = QLCDNumber(Dialog)
        self.CMDEcho.setObjectName(u"CMDEcho")
        self.CMDEcho.setGeometry(QRect(330, 230, 64, 23))
        self.line = QFrame(Dialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(420, 50, 20, 391))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(Dialog)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 40, 1111, 21))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(Dialog)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(0, 390, 431, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(Dialog)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(550, 440, 20, 341))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(Dialog)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(0, 620, 561, 20))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_6 = QFrame(Dialog)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(560, 530, 561, 20))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_7 = QFrame(Dialog)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(430, 430, 131, 20))
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.simEnable.setText(QCoreApplication.translate("Dialog", u"Simulation Enable", None))
        self.simActivate.setText(QCoreApplication.translate("Dialog", u"Simulation Activate", None))
        self.calAltitude.setText(QCoreApplication.translate("Dialog", u"Calibrate Altitude", None))
        self.totMissionTimeLabel.setText(QCoreApplication.translate("Dialog", u"Total Mission Time", None))
        self.packetCountLabel.setText(QCoreApplication.translate("Dialog", u"Packet Count", None))
        self.modeLabel.setText(QCoreApplication.translate("Dialog", u"Mode", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"UVA CavSat Ground Station - 1057", None))
        self.mode.setText(QCoreApplication.translate("Dialog", u"null", None))
        self.stateLabel.setText(QCoreApplication.translate("Dialog", u"State", None))
        self.state.setText(QCoreApplication.translate("Dialog", u"null", None))
        self.altitudeLabel.setText(QCoreApplication.translate("Dialog", u"Altitude", None))
        self.temperatureLabel.setText(QCoreApplication.translate("Dialog", u"Temperature", None))
        self.pressureLabel.setText(QCoreApplication.translate("Dialog", u"Pressure", None))
        self.voltageLabel.setText(QCoreApplication.translate("Dialog", u"Voltage", None))
        self.currentLabel.setText(QCoreApplication.translate("Dialog", u"Current", None))
        self.gyroRLabel.setText(QCoreApplication.translate("Dialog", u"Axis Information", None))
        self.pitchAxisLabel.setText(QCoreApplication.translate("Dialog", u"Pitch Axis", None))
        self.yawAxisLabel.setText(QCoreApplication.translate("Dialog", u"Yaw Axis ", None))
        self.gyroYLabel_2.setText(QCoreApplication.translate("Dialog", u"Accelerometer", None))
        self.rollAxisLabel.setText(QCoreApplication.translate("Dialog", u"Roll Axis", None))
        self.gyroRLabel_2.setText(QCoreApplication.translate("Dialog", u"Gyro", None))
        self.accelerometerRLabel.setText(QCoreApplication.translate("Dialog", u"Accelerometer", None))
        self.gyroPLabel_5.setText(QCoreApplication.translate("Dialog", u"Gyro", None))
        self.gyroPLabel_6.setText(QCoreApplication.translate("Dialog", u"Accelerometer", None))
        self.gyroYLabel_3.setText(QCoreApplication.translate("Dialog", u"Gyro", None))
        self.magRollLabel.setText(QCoreApplication.translate("Dialog", u"Magnetometer ", None))
        self.magYawLabel.setText(QCoreApplication.translate("Dialog", u"Magnetometer ", None))
        self.magPitchLabel.setText(QCoreApplication.translate("Dialog", u"Magnetometer ", None))
        self.autoGyroLabel.setText(QCoreApplication.translate("Dialog", u"Auto-Gyration Rate", None))
        self.GPSInfoLabel.setText(QCoreApplication.translate("Dialog", u"GPS Information", None))
        self.GPSTimeLabel.setText(QCoreApplication.translate("Dialog", u"Time", None))
        self.GPSAltitudeLabel.setText(QCoreApplication.translate("Dialog", u"Altitude", None))
        self.GPSLatitudeLabel.setText(QCoreApplication.translate("Dialog", u"Latitude", None))
        self.GPSLongitudeLabel.setText(QCoreApplication.translate("Dialog", u"Longitude", None))
        self.GPSsatsLabel.setText(QCoreApplication.translate("Dialog", u"Sats", None))
        self.CMDEchoLabel.setText(QCoreApplication.translate("Dialog", u"CMD Echo", None))
    # retranslateUi